import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowRight, CalendarDays, ChevronDown, ChevronRight, Compass, Headphones, Menu, MapPin, Phone, Play, Search, ShieldCheck, Ticket, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import heroImage from "@/assets/moar-hero.jpg";
import fleetImage from "@/assets/moar-fleet.jpg";

export const Route = createFileRoute("/")({
  component: Index,
  head: () => ({
    meta: [
      { title: "Moar Cars | Premium Self-Drive Rentals in Tirupati" },
      { name: "description", content: "Book premium self-drive cars in Tirupati with Moar Cars. Transparent pricing, flexible pickup and a fleet ready for every journey." },
      { property: "og:title", content: "Moar Cars | Drive More. Explore More." },
      { property: "og:description", content: "Premium self-drive cars in Tirupati for every journey." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
});

const fleet = [
  { name: "City Hatchbacks", detail: "Smart, efficient and easy to park", price: "₹1,699", tag: "Everyday", imagePosition: "left" },
  { name: "Executive Sedans", detail: "A smoother way to go further", price: "₹2,199", tag: "Comfort", imagePosition: "center" },
  { name: "Adventure SUVs", detail: "More room for the road ahead", price: "₹2,499", tag: "Popular", imagePosition: "right" },
];
const destinations = [
  { name: "Tirumala", detail: "Temple & pilgrimage", imagePosition: "left" },
  { name: "Chandragiri Fort", detail: "History & heritage", imagePosition: "center" },
  { name: "Horsley Hills", detail: "Weekend escape", imagePosition: "right" },
];
const benefits = [
  { icon: ShieldCheck, title: "Verified & maintained", copy: "Every car is checked before your key handover." },
  { icon: Ticket, title: "No surprise pricing", copy: "Clear rates, flexible plans and no hidden fees." },
  { icon: Compass, title: "Go beyond the usual", copy: "Curated road-trip inspiration from Tirupati." },
  { icon: Headphones, title: "Here when you need us", copy: "Real people and 24/7 roadside assistance." },
];

function Index() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [pickup, setPickup] = useState("Tirupati");
  const [startDate, setStartDate] = useState("2026-09-04");
  const [endDate, setEndDate] = useState("2026-09-06");
  const [notice, setNotice] = useState("");
  const [selectedFleet, setSelectedFleet] = useState("All cars");
  const handleSearch = () => {
    setNotice(`Showing cars available in ${pickup} from ${startDate} to ${endDate}.`);
    document.getElementById("fleet")?.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <main className="min-h-screen overflow-hidden bg-brand-cream text-brand-ink">
      <header className="fixed top-0 left-0 right-0 z-50 border-b border-primary-foreground/10 bg-brand-navy/80 backdrop-blur-md">
        <div className="relative mx-auto max-w-7xl px-5 py-4 sm:px-8 lg:px-10 flex items-center justify-between">
          <a href="#top" className="brand-mark flex items-center gap-2 text-xl tracking-tight text-primary-foreground" aria-label="Moar Cars home"><span className="flex h-9 w-9 items-center justify-center rounded-full border-2 border-brand-gold text-sm text-brand-gold">M</span><span>MOAR <span className="text-brand-gold">CARS</span></span></a>
          <nav className="hidden items-center gap-8 text-[11px] font-semibold uppercase tracking-[0.14em] text-primary-foreground/80 lg:flex"><a className="text-brand-gold" href="#top">Home</a><a className="transition-colors hover:text-brand-gold" href="#fleet">Our fleet</a><a className="transition-colors hover:text-brand-gold" href="#how-it-works">How it works</a><a className="transition-colors hover:text-brand-gold" href="#explore">Explore</a><a className="transition-colors hover:text-brand-gold" href="#about">About us</a></nav>
          <div className="hidden items-center gap-5 lg:flex"><a href="tel:+918500012345" className="flex items-center gap-2 text-xs font-medium text-primary-foreground/85"><Phone className="h-3.5 w-3.5 text-brand-gold" /> +91 85000 12345</a><Button className="h-10 rounded-sm bg-brand-gold px-5 text-xs font-bold uppercase tracking-[0.12em] text-brand-navy shadow-none hover:bg-brand-gold-soft" onClick={() => document.getElementById("booking")?.scrollIntoView({ behavior: "smooth" })}>Book a car <ArrowRight /></Button></div>
          <button className="rounded-sm p-2 text-primary-foreground lg:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? "Close navigation" : "Open navigation"}>{menuOpen ? <X /> : <Menu />}</button>
        </div>
        {menuOpen && <nav className="mx-auto max-w-7xl grid gap-3 px-5 pb-5 text-sm text-primary-foreground lg:hidden"><a href="#fleet" onClick={() => setMenuOpen(false)}>Our fleet</a><a href="#how-it-works" onClick={() => setMenuOpen(false)}>How it works</a><a href="#explore" onClick={() => setMenuOpen(false)}>Explore Tirupati</a><a href="#about" onClick={() => setMenuOpen(false)}>About us</a></nav>}
      </header>
      <section className="relative min-h-[calc(100vh-68px)] flex items-center pt-16 bg-brand-navy text-primary-foreground">
        <img src={heroImage} alt="SUV driving through the Tirupati hills" className="absolute inset-0 h-full w-full object-cover object-center" width={1600} height={900} />
        <div className="hero-wash absolute inset-0" /><div className="absolute inset-0 bg-brand-navy/10" />
        <div className="relative mx-auto w-full max-w-7xl px-5 py-12 sm:px-8 lg:px-10 flex flex-col justify-between gap-10">
          <div id="top" className="grid max-w-3xl gap-6 pt-4 sm:pt-6 lg:pt-8"><div className="animate-float-in flex items-center gap-3 text-xs font-bold uppercase tracking-[0.22em] text-brand-gold"><span className="gold-rule" /> Tirupati&apos;s premium car rental</div><h1 className="animate-float-in max-w-2xl text-5xl font-extrabold leading-[1.03] tracking-[-0.05em] sm:text-7xl" style={{ animationDelay: "80ms" }}>Your journey.<br />Your car.<br /><span className="text-brand-gold">Your way.</span></h1><p className="animate-float-in max-w-md text-base leading-7 text-primary-foreground/75 sm:text-lg" style={{ animationDelay: "160ms" }}>Take the long way home. Premium self-drive cars, simple booking and the freedom to explore Andhra Pradesh on your terms.</p><div className="animate-float-in flex flex-wrap items-center gap-4" style={{ animationDelay: "240ms" }}><Button className="h-12 rounded-sm bg-brand-gold px-6 font-bold text-brand-navy shadow-none hover:bg-brand-gold-soft" onClick={() => document.getElementById("booking")?.scrollIntoView({ behavior: "smooth" })}>Find your car <Search /></Button><a href="#how-it-works" className="group flex items-center gap-2 text-sm font-semibold text-primary-foreground/90">See how it works <span className="flex h-8 w-8 items-center justify-center rounded-full border border-primary-foreground/40 transition-colors group-hover:border-brand-gold group-hover:text-brand-gold"><Play className="h-3 w-3 fill-current" /></span></a></div></div>
          <div id="booking" className="w-full rounded-sm bg-brand-cream p-3 text-brand-ink shadow-2xl shadow-brand-navy/20 sm:p-4"><div className="grid gap-3 lg:grid-cols-[1.1fr_1fr_1fr_auto] lg:items-end"><label className="grid gap-1.5 px-2 text-[10px] font-bold uppercase tracking-[0.14em] text-muted-foreground">Pick-up location<span className="flex h-12 items-center gap-3 border-b border-border px-2 text-sm font-semibold normal-case tracking-normal"><MapPin className="h-4 w-4 text-brand-gold" /><select value={pickup} onChange={(event) => setPickup(event.target.value)} className="w-full bg-transparent outline-none"><option>Tirupati</option><option>Renigunta Airport</option><option>Chandragiri</option></select><ChevronDown className="h-4 w-4 text-muted-foreground" /></span></label><label className="grid gap-1.5 px-2 text-[10px] font-bold uppercase tracking-[0.14em] text-muted-foreground">Start date & time<span className="flex h-12 items-center gap-3 border-b border-border px-2"><CalendarDays className="h-4 w-4 text-brand-gold" /><input aria-label="Start date" type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} className="w-full bg-transparent text-sm font-semibold outline-none" /></span></label><label className="grid gap-1.5 px-2 text-[10px] font-bold uppercase tracking-[0.14em] text-muted-foreground">Return date & time<span className="flex h-12 items-center gap-3 border-b border-border px-2"><CalendarDays className="h-4 w-4 text-brand-gold" /><input aria-label="Return date" type="date" value={endDate} onChange={(event) => setEndDate(event.target.value)} className="w-full bg-transparent text-sm font-semibold outline-none" /></span></label><Button onClick={handleSearch} className="h-12 rounded-sm bg-brand-teal px-7 font-bold text-primary-foreground shadow-none hover:bg-brand-teal/90">Search cars <ArrowRight /></Button></div>{notice && <p role="status" className="px-2 pt-3 text-xs font-medium text-brand-teal">{notice}</p>}</div>
        </div>
      </section>
      <section className="border-b border-border bg-brand-cream py-16 sm:py-20"><div className="mx-auto grid max-w-7xl gap-8 px-5 sm:px-8 lg:grid-cols-4 lg:px-10">{benefits.map(({ icon: Icon, title, copy }) => <div key={title} className="flex gap-4 border-l border-border pl-5"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-brand-gold-soft text-brand-navy"><Icon className="h-5 w-5" /></span><div><h3 className="text-sm font-bold">{title}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{copy}</p></div></div>)}</div></section>
      <section id="fleet" className="page-grid scroll-mt-10 py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-brand-teal">The Moar collection</p><h2 className="mt-3 max-w-xl text-4xl font-extrabold leading-tight tracking-[-0.04em] sm:text-5xl">Find a car that feels like <span className="text-brand-teal">you.</span></h2></div><a href="#fleet" className="flex items-center gap-2 text-sm font-bold text-brand-navy hover:text-brand-teal">View all cars <ChevronRight className="h-4 w-4" /></a></div><div className="mt-9 flex flex-wrap gap-2" role="tablist" aria-label="Vehicle categories">{["All cars", "Hatchbacks", "Sedans", "SUVs"].map((filter) => <button key={filter} role="tab" aria-selected={selectedFleet === filter} onClick={() => setSelectedFleet(filter)} className={`rounded-full border px-4 py-2 text-xs font-bold transition-colors ${selectedFleet === filter ? "border-brand-navy bg-brand-navy text-primary-foreground" : "border-border bg-card text-muted-foreground hover:border-brand-teal hover:text-brand-teal"}`}>{filter}</button>)}</div><div className="mt-10 grid gap-5 lg:grid-cols-3">{fleet.map((car) => <article key={car.name} className="group overflow-hidden rounded-sm border border-border bg-card shadow-sm transition-transform hover:-translate-y-1"><div className="relative h-56 overflow-hidden bg-brand-navy"><img src={fleetImage} alt={`${car.name} vehicle collection`} loading="lazy" width={1600} height={1000} className={`h-full w-full object-cover transition-transform duration-700 group-hover:scale-105 ${car.imagePosition === "left" ? "object-left" : car.imagePosition === "right" ? "object-right" : "object-center"}`} /><span className="absolute left-4 top-4 rounded-full bg-brand-gold px-3 py-1 text-[10px] font-bold uppercase tracking-[0.12em] text-brand-navy">{car.tag}</span></div><div className="grid gap-5 p-5"><div><h3 className="text-xl font-bold">{car.name}</h3><p className="mt-1 text-sm text-muted-foreground">{car.detail}</p></div><div className="flex items-end justify-between border-t border-border pt-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-muted-foreground">From</p><p className="mt-1 text-lg font-extrabold text-brand-teal">{car.price}<span className="text-xs font-medium text-muted-foreground"> / day</span></p></div><Button variant="outline" className="rounded-sm border-brand-teal text-brand-teal hover:bg-brand-teal hover:text-primary-foreground" onClick={() => { setNotice(`${car.name} selected. Choose your dates above to continue.`); document.getElementById("booking")?.scrollIntoView({ behavior: "smooth" }); }}>Choose car <ArrowRight /></Button></div></div></article>)}</div></div></section>
      <section id="about" className="bg-brand-navy py-24 text-primary-foreground sm:py-32"><div className="mx-auto grid max-w-7xl gap-14 px-5 sm:px-8 lg:grid-cols-[0.85fr_1.15fr] lg:items-center lg:px-10"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-brand-gold">More than a rental</p><h2 className="mt-4 text-4xl font-extrabold leading-tight tracking-[-0.04em] sm:text-5xl">The best stories start when you <span className="text-brand-gold">take the wheel.</span></h2><p className="mt-6 max-w-md text-base leading-7 text-primary-foreground/70">We make self-drive simple, so you can spend less time organising and more time discovering. From an early temple visit to a late-night hill drive, your next chapter starts here.</p><a href="#how-it-works" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-brand-gold">Why drive with Moar <ArrowRight className="h-4 w-4" /></a></div><div className="relative overflow-hidden rounded-sm border border-primary-foreground/15"><img src={heroImage} alt="Road winding through the hills around Tirupati" loading="lazy" width={1600} height={900} className="h-[360px] w-full object-cover sm:h-[450px]" /><div className="absolute bottom-5 left-5 right-5 flex items-center justify-between border border-primary-foreground/20 bg-brand-navy/80 p-4 backdrop-blur-sm"><div><p className="text-2xl font-extrabold">50+</p><p className="text-xs text-primary-foreground/60">cars ready to go</p></div><div className="h-9 w-px bg-primary-foreground/20" /><div><p className="text-2xl font-extrabold">4.9/5</p><p className="text-xs text-primary-foreground/60">traveller rating</p></div><div className="h-9 w-px bg-primary-foreground/20" /><div><p className="text-2xl font-extrabold">24/7</p><p className="text-xs text-primary-foreground/60">roadside care</p></div></div></div></div></section>
      <section id="explore" className="bg-brand-cream py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="flex items-end justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-brand-teal">Make a day of it</p><h2 className="mt-3 text-4xl font-extrabold tracking-[-0.04em] sm:text-5xl">Explore from Tirupati.</h2></div><Compass className="hidden h-12 w-12 text-brand-gold sm:block" /></div><div className="mt-10 grid gap-5 md:grid-cols-3">{destinations.map((destination) => <a key={destination.name} href="#booking" className="group relative h-72 overflow-hidden rounded-sm bg-brand-navy"><img src={heroImage} alt={destination.name} loading="lazy" width={1600} height={900} className={`h-full w-full object-cover opacity-80 transition duration-700 group-hover:scale-105 group-hover:opacity-100 ${destination.imagePosition === "left" ? "object-left" : destination.imagePosition === "right" ? "object-right" : "object-center"}`} /><div className="absolute inset-0 bg-gradient-to-t from-brand-navy via-brand-navy/15 to-transparent" /><div className="absolute bottom-5 left-5 text-primary-foreground"><p className="text-xl font-bold">{destination.name}</p><p className="mt-1 text-xs text-primary-foreground/70">{destination.detail}</p></div><span className="absolute right-5 top-5 flex h-9 w-9 items-center justify-center rounded-full bg-brand-gold text-brand-navy transition-transform group-hover:translate-x-1"><ArrowRight className="h-4 w-4" /></span></a>)}</div></div></section>
      <section id="how-it-works" className="border-y border-border bg-brand-mist py-20 sm:py-24"><div className="mx-auto grid max-w-7xl gap-12 px-5 sm:px-8 lg:grid-cols-[0.8fr_1.2fr] lg:px-10"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-brand-teal">Simple by design</p><h2 className="mt-3 text-4xl font-extrabold tracking-[-0.04em]">Your road, in four easy steps.</h2></div><div className="grid gap-0 sm:grid-cols-4">{[{ n: "01", title: "Choose", copy: "Pick a car that fits your day." }, { n: "02", title: "Reserve", copy: "Select dates and lock it in." }, { n: "03", title: "Collect", copy: "Meet us or choose doorstep delivery." }, { n: "04", title: "Drive", copy: "Turn the key and go your way." }].map((step, index) => <div key={step.n} className="relative border-l border-brand-teal/30 py-4 pl-5 sm:py-0"><span className="text-xs font-bold text-brand-gold">{step.n}</span><h3 className="mt-5 text-lg font-bold">{step.title}</h3><p className="mt-2 pr-4 text-xs leading-5 text-muted-foreground">{step.copy}</p>{index < 3 && <ChevronRight className="absolute -right-2 top-1/2 hidden h-4 w-4 bg-brand-mist text-brand-teal sm:block" />}</div>)}</div></div></section>
      <footer className="bg-brand-ink py-14 text-primary-foreground"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="grid gap-12 border-b border-primary-foreground/15 pb-12 md:grid-cols-[1.4fr_1fr_1fr_1fr]"><div><a href="#top" className="brand-mark flex items-center gap-2 text-xl"><span className="flex h-9 w-9 items-center justify-center rounded-full border-2 border-brand-gold text-sm text-brand-gold">M</span> MOAR <span className="text-brand-gold">CARS</span></a><p className="mt-5 max-w-xs text-sm leading-6 text-primary-foreground/55">Drive more. Explore more. Premium self-drive cars for every Tirupati story.</p><div className="mt-5 flex items-center gap-2 text-xs text-primary-foreground/60"><MapPin className="h-4 w-4 text-brand-gold" /> Tirupati, Andhra Pradesh</div></div><div><h3 className="text-xs font-bold uppercase tracking-[0.16em] text-brand-gold">Discover</h3><div className="mt-5 grid gap-3 text-sm text-primary-foreground/65"><a href="#fleet" className="hover:text-brand-gold">Our fleet</a><a href="#explore" className="hover:text-brand-gold">Explore Tirupati</a><a href="#how-it-works" className="hover:text-brand-gold">How it works</a></div></div><div><h3 className="text-xs font-bold uppercase tracking-[0.16em] text-brand-gold">Company</h3><div className="mt-5 grid gap-3 text-sm text-primary-foreground/65"><a href="#about" className="hover:text-brand-gold">About Moar</a><a href="mailto:hello@moarcars.in" className="hover:text-brand-gold">Contact us</a><a href="#booking" className="hover:text-brand-gold">Book a car</a></div></div><div><h3 className="text-xs font-bold uppercase tracking-[0.16em] text-brand-gold">Need a hand?</h3><a href="tel:+918500012345" className="mt-5 flex items-center gap-2 text-sm text-primary-foreground/65 hover:text-brand-gold"><Phone className="h-4 w-4" /> +91 85000 12345</a><p className="mt-3 text-xs text-primary-foreground/45">Available every day, all day.</p></div></div><div className="flex flex-col justify-between gap-4 pt-7 text-xs text-primary-foreground/40 sm:flex-row"><p>© 2026 Moar Cars. All rights reserved.</p><p>Made for the road ahead.</p></div></div></footer>
    </main>
  );
}
