import sqlite3 from "sqlite3";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const defaultCars = [
  {
    id: 1,
    name: "Maruti Swift ZXi+",
    brand: "Maruti Suzuki",
    model: "Swift",
    variant: "ZXi Plus Dual Tone",
    year: 2024,
    registrationNumber: "AP 03 TX 1024",
    vinNumber: "MA3EYD21S00192844",
    detail: "Smart 5-seater hatchback, agile city commuter with touch infotainment & fuel efficiency",
    price: "₹1,699",
    pricePerHour: 199,
    pricePerDay: 1699,
    pricePerWeek: 9999,
    pricePerMonth: 34999,
    securityDeposit: 3000,
    lateFeePerHour: 150,
    tag: "Everyday",
    category: "Hatchback",
    fuelType: "Petrol",
    transmission: "Manual",
    seats: 5,
    mileage: "22 km/l",
    color: "Pearl Arctic White",
    status: "Available",
    branch: "Tirupati Central Hub",
    location: "Tirupati",
    gpsEnabled: 1,
    fastagNumber: "FTG-889021-39",
    insuranceExpiry: "2027-04-15",
    pollutionExpiry: "2026-11-20",
    fitnessExpiry: "2028-08-10",
    permitExpiry: "2027-12-31",
    image: "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=800&q=80",
    totalTrips: 42,
    totalRevenue: 71358,
    maintenanceCost: 4500,
    isArchived: 0
  },
  {
    id: 2,
    name: "Honda City ZX Automatic",
    brand: "Honda",
    model: "City",
    variant: "ZX CVT Sunroof",
    year: 2024,
    registrationNumber: "AP 03 DX 5088",
    vinNumber: "MAKGM21S00288190",
    detail: "Executive sedan with electric sunroof, leather upholstery, and ADAS Level 2 safety",
    price: "₹2,199",
    pricePerHour: 249,
    pricePerDay: 2199,
    pricePerWeek: 12999,
    pricePerMonth: 44999,
    securityDeposit: 4000,
    lateFeePerHour: 200,
    tag: "Comfort",
    category: "Sedan",
    fuelType: "Petrol",
    transmission: "Automatic",
    seats: 5,
    mileage: "18 km/l",
    color: "Platinum White Pearl",
    status: "Available",
    branch: "Renigunta Airport Hub",
    location: "Renigunta",
    gpsEnabled: 1,
    fastagNumber: "FTG-994012-77",
    insuranceExpiry: "2027-02-10",
    pollutionExpiry: "2026-10-15",
    fitnessExpiry: "2028-05-12",
    permitExpiry: "2027-11-20",
    image: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
    totalTrips: 36,
    totalRevenue: 79164,
    maintenanceCost: 6200,
    isArchived: 0
  },
  {
    id: 3,
    name: "Mahindra Scorpio-N Z8L 4x4",
    brand: "Mahindra",
    model: "Scorpio-N",
    variant: "Z8L 4x4 Automatic Diesel",
    year: 2024,
    registrationNumber: "AP 03 ZX 9900",
    vinNumber: "MA1Z8L44A00993812",
    detail: "Dominant 7-seater luxury SUV, 4Xplorer terrain modes for Tirumala ghat roads",
    price: "₹2,499",
    pricePerHour: 299,
    pricePerDay: 2499,
    pricePerWeek: 14999,
    pricePerMonth: 54999,
    securityDeposit: 5000,
    lateFeePerHour: 250,
    tag: "Popular",
    category: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    seats: 7,
    mileage: "15 km/l",
    color: "Napoli Black",
    status: "Booked",
    branch: "Tirupati Central Hub",
    location: "Tirupati",
    gpsEnabled: 1,
    fastagNumber: "FTG-771120-45",
    insuranceExpiry: "2027-08-30",
    pollutionExpiry: "2026-09-25",
    fitnessExpiry: "2029-01-15",
    permitExpiry: "2028-04-10",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
    totalTrips: 48,
    totalRevenue: 119952,
    maintenanceCost: 8900,
    isArchived: 0
  },
  {
    id: 4,
    name: "Toyota Innova Crysta ZX",
    brand: "Toyota",
    model: "Innova Crysta",
    variant: "2.4 ZX Captain Seats",
    year: 2024,
    registrationNumber: "AP 03 AX 7777",
    vinNumber: "MB7CRYS2400777123",
    detail: "Unmatched pilgrimage luxury, captain seats with climate control & ample luggage space",
    price: "₹3,499",
    pricePerHour: 399,
    pricePerDay: 3499,
    pricePerWeek: 20999,
    pricePerMonth: 74999,
    securityDeposit: 6000,
    lateFeePerHour: 300,
    tag: "Luxury",
    category: "Luxury",
    fuelType: "Diesel",
    transmission: "Automatic",
    seats: 7,
    mileage: "14 km/l",
    color: "Super White",
    status: "Available",
    branch: "Chandragiri Heritage Point",
    location: "Chandragiri",
    gpsEnabled: 1,
    fastagNumber: "FTG-556677-88",
    insuranceExpiry: "2027-06-18",
    pollutionExpiry: "2026-12-05",
    fitnessExpiry: "2029-03-20",
    permitExpiry: "2028-06-15",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
    totalTrips: 29,
    totalRevenue: 101471,
    maintenanceCost: 5100,
    isArchived: 0
  },
  {
    id: 5,
    name: "Hyundai Creta SX(O)",
    brand: "Hyundai",
    model: "Creta",
    variant: "SX(O) Turbo DCT",
    year: 2024,
    registrationNumber: "AP 03 KX 4421",
    vinNumber: "MALHC81SB00399120",
    detail: "Panoramic sunroof, ventilated front seats, premium Bose audio system",
    price: "₹2,299",
    pricePerHour: 259,
    pricePerDay: 2299,
    pricePerWeek: 13999,
    pricePerMonth: 48999,
    securityDeposit: 4000,
    lateFeePerHour: 200,
    tag: "Popular",
    category: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    seats: 5,
    mileage: "17 km/l",
    color: "Ranger Khaki",
    status: "In Maintenance",
    branch: "Tirupati Central Hub",
    location: "Tirupati",
    gpsEnabled: 1,
    fastagNumber: "FTG-112233-44",
    insuranceExpiry: "2027-05-18",
    pollutionExpiry: "2026-10-30",
    fitnessExpiry: "2028-09-15",
    permitExpiry: "2027-11-20",
    image: "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80",
    totalTrips: 31,
    totalRevenue: 71269,
    maintenanceCost: 3800,
    isArchived: 0
  }
];

function populateDb(filePath) {
  const db = new sqlite3.Database(filePath, (err) => {
    if (err) return console.error("Error opening", filePath, err);
    db.serialize(() => {
      db.run("DELETE FROM Cars");
      
      const stmt = db.prepare(`INSERT OR REPLACE INTO Cars (
        id, name, brand, model, variant, year, registrationNumber, vinNumber, detail, price,
        pricePerHour, pricePerDay, pricePerWeek, pricePerMonth, securityDeposit, lateFeePerHour,
        tag, category, fuelType, transmission, seats, mileage, color, status, branch, location,
        gpsEnabled, fastagNumber, insuranceExpiry, pollutionExpiry, fitnessExpiry, permitExpiry,
        image, totalTrips, totalRevenue, maintenanceCost, isArchived, createdAt, updatedAt
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'), datetime('now'))`);

      for (const c of defaultCars) {
        stmt.run(
          c.id, c.name, c.brand, c.model, c.variant, c.year, c.registrationNumber, c.vinNumber, c.detail, c.price,
          c.pricePerHour, c.pricePerDay, c.pricePerWeek, c.pricePerMonth, c.securityDeposit, c.lateFeePerHour,
          c.tag, c.category, c.fuelType, c.transmission, c.seats, c.mileage, c.color, c.status, c.branch, c.location,
          c.gpsEnabled, c.fastagNumber, c.insuranceExpiry, c.pollutionExpiry, c.fitnessExpiry, c.permitExpiry,
          c.image, c.totalTrips, c.totalRevenue, c.maintenanceCost, c.isArchived
        );
      }
      stmt.finalize(() => {
        console.log("Successfully seeded", filePath, "with", defaultCars.length, "vehicles!");
      });
    });
  });
}

populateDb(path.join(__dirname, "database.sqlite"));
populateDb(path.join(__dirname, "moar_database.sqlite"));
