import {
  CMSBannerItem,
  CMSOfferItem,
  CMSTestimonialItem,
  CMSFaqItem,
  CMSBlogItem,
  NotificationTemplateItem,
  ReviewItem,
  SupportTicketItem,
  ActivityLogItem,
} from "./types";

export const initialBanners: CMSBannerItem[] = [
  {
    id: 1,
    title: "Tirumala Darshan & Pilgrimage Self-Drive",
    subtitle: "Sanitized SUVs & Sedans with instant doorstep delivery across Tirupati & Airport",
    imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    ctaText: "Book Now @ ₹1,699/day",
    ctaLink: "/fleet",
    isActive: true,
  },
  {
    id: 2,
    title: "Luxury Chauffeur Service for Corporate & VIPs",
    subtitle: "Professional verified drivers with ghat road experience & 24/7 road assistance",
    imageUrl: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80",
    ctaText: "Explore Chauffeur Fleet",
    ctaLink: "/chauffeur",
    isActive: true,
  },
];

export const initialOffers: CMSOfferItem[] = [
  {
    id: 1,
    title: "Brahmotsavam Pilgrimage Special",
    tag: "Festival Offer",
    discountText: "Flat ₹500 OFF on 2+ Days",
    description: "Use code MOARFIRST on SUV & 7-Seater bookings. Free temple parking pass assistance.",
    validTill: "31 Oct 2026",
    badge: "Most Popular",
    imageUrl: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=600&q=80",
    isActive: true,
  },
  {
    id: 2,
    title: "Airport Doorstep Delivery Free",
    tag: "Renigunta Airport",
    discountText: "100% Free Handover @ Terminal 1",
    description: "Touchdown and drive away. Zero terminal delivery charges for advance flight bookings.",
    validTill: "31 Dec 2026",
    badge: "Airport Special",
    imageUrl: "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=600&q=80",
    isActive: true,
  },
];

export const initialTestimonials: CMSTestimonialItem[] = [
  {
    id: 1,
    name: "Dr. K. Sreenivas",
    role: "Pilgrim Traveler",
    city: "Hyderabad",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    rating: 5,
    comment: "Took the Scorpio-N for Tirumala ghat road trip with family. Absolutely spotless car, seamless OTP delivery at Tirupati railway station!",
    carRented: "Mahindra Scorpio-N Z8L",
    isFeatured: true,
  },
  {
    id: 2,
    name: "Pooja Hegde",
    role: "IT Consultant",
    city: "Bengaluru",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    rating: 5,
    comment: "Rented Honda City Automatic from Renigunta airport. Deposit refunded within 10 minutes of return. Top notch service!",
    carRented: "Honda City ZX Automatic",
    isFeatured: true,
  },
];

export const initialFaqs: CMSFaqItem[] = [
  {
    id: 1,
    category: "Documents",
    question: "What documents are required to rent a self-drive car with Moar Cars?",
    answer: "You need a valid Original Indian Driving License (minimum 1 year old) and Government ID (Aadhaar Card or Passport). International tourists can provide Passport & International Driving Permit (IDP).",
  },
  {
    id: 2,
    category: "Security Deposit",
    question: "How and when is the security deposit refunded?",
    answer: "Security deposits (₹3,000 to ₹6,000 based on car category) are held in secure escrow and released immediately via UPI or bank transfer after the vehicle return inspection is completed.",
  },
  {
    id: 3,
    category: "Bookings",
    question: "Are fuel and FASTag toll charges included in the rental price?",
    answer: "Our cars are delivered with full/recorded fuel. You can return with the same level. All cars are equipped with FASTag; toll charges are auto-reconciled at checkout.",
  },
];

export const initialBlogs: CMSBlogItem[] = [
  {
    id: 1,
    title: "Complete Guide to Driving to Tirumala: Rules, Timings & Best Cars",
    slug: "tirumala-driving-guide-2026",
    category: "Pilgrimage Guide",
    author: "Moar Travel Desk",
    date: "Sep 2, 2026",
    readTime: "4 min read",
    summary: "Everything you need to know about the 1st & 2nd ghat roads, toll checkposts, hill driving tips, and vehicle speed limits in Tirupati.",
    imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=80",
    isPublished: true,
  },
  {
    id: 2,
    title: "Top 5 Weekend Getaways from Tirupati within 150 km",
    slug: "top-5-weekend-getaways-tirupati",
    category: "Road Trips",
    author: "Ravi Teja",
    date: "Aug 28, 2026",
    readTime: "5 min read",
    summary: "Discover Horsley Hills, Talakona Waterfalls, Chandragiri Fort, and Kaigal Falls with self-drive rentals.",
    imageUrl: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=600&q=80",
    isPublished: true,
  },
];

export const initialNotificationTemplates: NotificationTemplateItem[] = [
  {
    id: "NOTIF-01",
    channel: "WhatsApp",
    trigger: "Booking Confirmation",
    body: "Namaste {{customer_name}}! 🚗 Your Moar Cars booking #{{booking_id}} for {{car_name}} is CONFIRMED from {{start_date}} to {{end_date}}. Station: {{pickup_station}}. Have a safe pilgrimage!",
    isActive: true,
  },
  {
    id: "NOTIF-02",
    channel: "SMS",
    trigger: "Pickup Reminder",
    body: "Moar Cars Alert: Your vehicle {{car_name}} is ready for pickup at {{pickup_station}}. Handover Agent: {{staff_name}} ({{staff_phone}}). Please carry original DL.",
    isActive: true,
  },
  {
    id: "NOTIF-03",
    channel: "WhatsApp",
    trigger: "Return Reminder",
    body: "Hi {{customer_name}}, gentle reminder that your trip for {{car_name}} ends at {{end_date}}. Please ensure fuel level matches pickup. Return Station: {{drop_station}}.",
    isActive: true,
  },
  {
    id: "NOTIF-04",
    channel: "Email",
    trigger: "Payment Reminder",
    subject: "Moar Cars: Security Deposit Released for Booking #{{booking_id}}",
    body: "Dear {{customer_name}}, Your security deposit of ₹{{deposit_amount}} for Booking #{{booking_id}} has been refunded successfully via UPI txn #{{txn_id}}.",
    isActive: true,
  },
  {
    id: "NOTIF-05",
    channel: "Push",
    trigger: "KYC Document Request",
    body: "Upload your Driving License to complete instant 2-minute KYC verification for fast contactless pickup.",
    isActive: true,
  },
];

export const initialReviews: ReviewItem[] = [
  {
    id: 601,
    customerName: "Rajesh Varma",
    customerPhone: "+91 98765 11223",
    carName: "Mahindra Scorpio-N Z8L 4x4",
    rating: 5,
    comment: "Superb vehicle condition. Scorpio-N handled the ghat roads with effortless torque. Handover at Tirupati station was on time.",
    date: "2026-09-03",
    status: "Approved",
    isFeatured: true,
    adminReply: "Thank you Rajesh garu! Glad you enjoyed your pilgrimage trip with Moar Cars.",
  },
  {
    id: 602,
    customerName: "Ananya Sharma",
    customerPhone: "+91 98480 33445",
    carName: "Honda City ZX Automatic",
    rating: 5,
    comment: "Clean interiors, pleasant fragrance, smooth automatic transmission. Customer support on WhatsApp was prompt.",
    date: "2026-09-02",
    status: "Approved",
    isFeatured: true,
  },
  {
    id: 603,
    customerName: "Sanjay Gupta",
    customerPhone: "+91 97000 88221",
    carName: "Maruti Swift ZXi+",
    rating: 4,
    comment: "Good mileage and easy parking near Tirumala cottage area. AC was powerful.",
    date: "2026-09-01",
    status: "Approved",
    isFeatured: false,
  },
  {
    id: 604,
    customerName: "Karthik Raj",
    customerPhone: "+91 95500 11990",
    carName: "Toyota Innova Crysta ZX",
    rating: 2,
    comment: "Driver arrived 15 minutes late due to traffic near Alipiri checkpost.",
    date: "2026-08-30",
    status: "Pending",
    isFeatured: false,
    adminReply: "Apologies Karthik. We have audited the dispatch team and credited ₹500 to your Moar Wallet.",
  },
];

export const initialSupportTickets: SupportTicketItem[] = [
  {
    id: "TKT-8801",
    customerName: "Rajesh Varma",
    customerPhone: "+91 98765 11223",
    bookingId: 1042,
    category: "Booking Issue",
    priority: "High",
    status: "Open",
    assignedAgent: "M. Ramesh Reddy",
    subject: "Need child booster seat added for Scorpio-N trip tomorrow",
    messages: [
      { sender: "Customer", text: "Hello, can you please arrange a child booster seat for booking #1042?", time: "6:45 PM" },
      { sender: "Agent", text: "Namaste Rajesh garu! We have reserved an ISOFIX child seat at Tirupati Central Hub at zero extra cost.", time: "6:50 PM" },
    ],
    createdAt: "2026-09-04 18:45",
  },
  {
    id: "TKT-8802",
    customerName: "Vikram Rathore",
    customerPhone: "+91 94401 77889",
    bookingId: 1040,
    category: "KYC Verification",
    priority: "Medium",
    status: "In Progress",
    assignedAgent: "Kiran Reddy",
    subject: "Aadhaar back photo re-uploaded for verification",
    messages: [
      { sender: "Customer", text: "I have re-uploaded the clear picture of my Aadhaar card.", time: "11:30 AM" },
      { sender: "Agent", text: "Reviewing your document right now. Will approve in 5 minutes.", time: "11:35 AM" },
    ],
    createdAt: "2026-09-04 11:30",
  },
  {
    id: "TKT-8803",
    customerName: "Praveen Rao",
    customerPhone: "+91 98852 99001",
    bookingId: 1039,
    category: "Payment / Refund",
    priority: "Low",
    status: "Resolved",
    assignedAgent: "Ravi Teja",
    subject: "Security deposit refund status enquiry",
    messages: [
      { sender: "Customer", text: "When will the ₹3,000 security deposit reflect in my bank account?", time: "Sep 2, 9:00 AM" },
      { sender: "Agent", text: "Refund #UPI_TXN_771928301928 has been processed. It should reflect within 15 minutes.", time: "Sep 2, 9:05 AM" },
      { sender: "Customer", text: "Received, thank you!", time: "Sep 2, 9:20 AM" },
    ],
    createdAt: "2026-09-02 09:00",
  },
];

export const initialActivityLogs: ActivityLogItem[] = [
  {
    id: "LOG-1001",
    timestamp: "2026-09-04 18:35:10",
    adminName: "Executive Super Admin",
    module: "Bookings",
    action: "Assigned Chauffeur",
    details: "Assigned Suresh Kumar (+91 98765 00001) to Booking #1042",
    ipAddress: "122.179.88.14 (Chrome Windows)",
  },
  {
    id: "LOG-1002",
    timestamp: "2026-09-04 18:30:22",
    adminName: "Executive Super Admin",
    module: "Payments",
    action: "Captured Advance Payment",
    details: "Captured ₹4,998 + ₹5,000 deposit via UPI gateway for Booking #1042",
    ipAddress: "122.179.88.14 (Chrome Windows)",
  },
  {
    id: "LOG-1003",
    timestamp: "2026-09-04 16:10:45",
    adminName: "Executive Super Admin",
    module: "Fleet",
    action: "Updated Vehicle Health",
    details: "Logged 25,000 km routine service audit for Mahindra Scorpio-N (AP 03 ZX 9900)",
    ipAddress: "122.179.88.14 (Chrome Windows)",
  },
  {
    id: "LOG-1004",
    timestamp: "2026-09-04 14:15:00",
    adminName: "Executive Super Admin",
    module: "Customers",
    action: "KYC Approved",
    details: "Approved Driving License & Aadhaar verification for Ananya Sharma (ID #202)",
    ipAddress: "122.179.88.14 (Chrome Windows)",
  },
  {
    id: "LOG-1005",
    timestamp: "2026-09-04 11:00:15",
    adminName: "Executive Super Admin",
    module: "Coupons",
    action: "Created Promotional Coupon",
    details: "Activated code 'MOARFIRST' with ₹500 flat discount and min booking ₹2,500",
    ipAddress: "122.179.88.14 (Chrome Windows)",
  },
];
